/**
 * Inhalt der Seite „Ressourcen & Tools“ — zentral pflegbar.
 */
export const resourcesPageConfig = {
  resourceSections: [
    {
      id: "research-question",
      title: "1. Forschungsfrage formulieren & schärfen",
      intro:
        "Tools zur Ideenfindung, Eingrenzung und Prüfung von Forschungsfragen. KI unterstützt hier beim Strukturieren, ersetzt aber keine fachliche Bewertung.",
      links: [
        {
          id: "chatgpt",
          label: "ChatGPT / OpenAI",
          description: "Formulierung, Strukturierung und kritische Prüfung von Forschungsfragen.",
          href: "https://chatgpt.com/",
          type: "KI",
          purpose: "PICOC/SPIDER/CIMO-Fragen formulieren und FINER-Kriterien prüfen",
          caution: "Kein Ersatz für Quellenarbeit; Ergebnisse fachlich und methodisch prüfen.",
        },
        {
          id: "elicit",
          label: "Elicit",
          description: "KI-gestützte Paper-Suche, Forschungsüberblick und Extraktion.",
          href: "https://elicit.com/",
          type: "KI / Forschung",
          purpose: "Aus Forschungsideen relevante Literatur, mögliche Variablen und Forschungslücken ableiten",
          caution: "Gefundene Quellen und Zusammenfassungen immer am Originalpaper prüfen.",
        },
        {
          id: "consensus",
          label: "Consensus",
          description: "KI-Suchmaschine für wissenschaftliche Evidenz aus Publikationen.",
          href: "https://consensus.app/",
          type: "KI / Evidenz",
          purpose: "Erste Einschätzung, ob zu einer Forschungsfrage belastbare Evidenz existiert",
          caution: "Nicht als alleinige Datenbank für eine SLR verwenden.",
        },
        {
          id: "perplexity",
          label: "Perplexity",
          description: "Antwortmaschine mit Quellenangaben für schnelle Orientierung.",
          href: "https://www.perplexity.ai/",
          type: "KI / Web",
          purpose: "Begriffe, Synonyme, Anwendungskontexte und Einstiegsliteratur sammeln",
          caution: "Webquellen von wissenschaftlichen Quellen trennen.",
        },
      ],
    },
    {
      id: "search-screening",
      title: "2. Suchstrategie, Datenbanken & Screening",
      intro:
        "Tools zur systematischen Suche, Dokumentation und Auswahl von Literatur. Ziel ist ein reproduzierbarer Such- und Screening-Prozess.",
      links: [
        {
          id: "semantic-scholar",
          label: "Semantic Scholar",
          description: "KI-gestützte wissenschaftliche Suchmaschine.",
          href: "https://www.semanticscholar.org/",
          type: "Datenbank / KI",
          purpose: "Relevante Papers, verwandte Arbeiten und Zitationsbeziehungen finden",
          caution: "Suchstrategie zusätzlich in geeigneten Fachdatenbanken dokumentieren.",
        },
        {
          id: "openalex",
          label: "OpenAlex",
          description: "Offener Katalog wissenschaftlicher Werke, Autor:innen, Institutionen und Quellen.",
          href: "https://openalex.org/",
          type: "Metadaten / Open",
          purpose: "Publikations- und Metadaten prüfen, Quellenkontexte nachvollziehen",
          caution: "Metadaten können unvollständig sein; bei wichtigen Quellen DOI/Verlag gegenprüfen.",
        },
        {
          id: "rayyan",
          label: "Rayyan",
          description: "Review-Plattform für Titel-/Abstract-Screening und Kollaboration.",
          href: "https://www.rayyan.ai/",
          type: "Screening",
          purpose: "Treffer importieren, labeln, ein-/ausschließen und Entscheidungen dokumentieren",
          caution: "KI-Priorisierung unterstützt nur; finale Entscheidungen müssen begründet werden.",
        },
        {
          id: "covidence",
          label: "Covidence",
          description: "Systematic-Review-Software für Screening, Extraktion und Teamarbeit.",
          href: "https://www.covidence.org/",
          type: "Review-Management",
          purpose: "Screening-Workflows und Datenextraktion professionell organisieren",
          caution: "Eher umfangreich/kommerziell; für kleine studentische Reviews ggf. zu groß.",
        },
      ],
    },
    {
      id: "analysis-coding",
      title: "3. Analyse & Kodierung",
      intro:
        "Tools zur qualitativen Analyse, Kategorienbildung und Arbeit mit Kodierleitfäden. KI kann Vorschläge machen, die Kodierung muss jedoch methodisch kontrolliert werden.",
      links: [
        {
          id: "maxqda",
          label: "MAXQDA AI Assist",
          description: "Qualitative Datenanalyse mit KI-Unterstützung für Zusammenfassungen und Codes.",
          href: "https://www.maxqda.com/products/ai-assist",
          type: "QDA / KI",
          purpose: "Kategorien, Subcodes und Zusammenfassungen für kodierte Segmente entwickeln",
          caution: "KI-Vorschläge mit Kodierleitfaden und Originaltext abgleichen.",
        },
        {
          id: "atlasti",
          label: "ATLAS.ti",
          description: "Qualitative Datenanalyse mit KI-Funktionen für Dokumente und Kodierung.",
          href: "https://atlasti.com/",
          type: "QDA / KI",
          purpose: "Textstellen analysieren, Codes entwickeln und Dokumente systematisch auswerten",
          caution: "Automatische Kodierung nicht ungeprüft übernehmen.",
        },
        {
          id: "nvivo",
          label: "NVivo",
          description: "Etabliertes Tool für qualitative und Mixed-Methods-Analyse.",
          href: "https://lumivero.com/products/nvivo/",
          type: "QDA",
          purpose: "Literatur, Notizen, Codes und Auswertungen in einem Projekt organisieren",
          caution: "Für kurze Workshop-Übungen ggf. zu umfangreich; eher als Referenztool nennen.",
        },
        {
          id: "taguette",
          label: "Taguette",
          description: "Freies Open-Source-Tool zum Markieren, Taggen und Exportieren qualitativer Daten.",
          href: "https://www.taguette.org/",
          type: "Open Source / QDA",
          purpose: "Einfaches Kodieren von Textstellen ohne kommerzielle Lizenz",
          caution: "Weniger Funktionsumfang als MAXQDA, ATLAS.ti oder NVivo.",
        },
      ],
    },
    {
      id: "concept-matrix",
      title: "4. Konzeptmatrix, Literaturmapping & Forschungslücken",
      intro:
        "Tools zur visuellen Erschließung des Forschungsfelds, zur Identifikation verwandter Arbeiten und zur Entwicklung von Forschungslücken.",
      links: [
        {
          id: "connected-papers",
          label: "Connected Papers",
          description: "Visuelles Tool zum Finden und Erkunden verwandter wissenschaftlicher Arbeiten.",
          href: "https://www.connectedpapers.com/",
          type: "Mapping",
          purpose: "Literaturcluster, zentrale Arbeiten und angrenzende Forschungsstränge erkennen",
          caution: "Visualisierung ergänzt die Suche, ersetzt aber keine dokumentierte Suchstrategie.",
        },
        {
          id: "researchrabbit",
          label: "ResearchRabbit",
          description: "Literaturmapping, Citation Maps und Trendbeobachtung.",
          href: "https://www.researchrabbit.ai/",
          type: "Mapping / KI",
          purpose: "Ausgehend von Seed-Papers verwandte Literatur und Forschungsentwicklungen finden",
          caution: "Startpaper bewusst wählen, sonst entstehen verzerrte Literaturcluster.",
        },
        {
          id: "litmaps",
          label: "Litmaps",
          description: "Literaturkarten und Zitationspfade für Literature Discovery.",
          href: "https://www.litmaps.com/",
          type: "Mapping",
          purpose: "Themenfelder, Paper-Verbindungen und mögliche Forschungslücken sichtbar machen",
          caution: "Nicht jede Lücke im Mapping ist automatisch eine wissenschaftliche Forschungslücke.",
        },
        {
          id: "scite",
          label: "scite.ai",
          description: "Smart Citations zeigen, wie Paper von anderen Arbeiten zitiert werden.",
          href: "https://scite.ai/",
          type: "Zitationsanalyse / KI",
          purpose: "Unterstützende, kontrastierende oder erwähnende Zitationskontexte prüfen",
          caution: "Zitationskontext immer mit dem Originalpaper interpretieren.",
        },
      ],
    },
  ],

  baseLinks: [
    {
      id: "google-scholar",
      label: "Google Scholar",
      href: "https://scholar.google.com/",
      type: "Datenbank",
    },
    {
      id: "crossref",
      label: "Crossref",
      href: "https://www.crossref.org/",
      type: "Metadaten",
    },
    {
      id: "base",
      label: "BASE",
      href: "https://www.base-search.net/",
      type: "Datenbank / Open",
    },
    {
      id: "unpaywall",
      label: "Unpaywall / OADOI",
      href: "https://unpaywall.org/",
      type: "Open Access",
    },
    {
      id: "prisma",
      label: "PRISMA",
      href: "https://www.prisma-statement.org/",
      type: "Reporting",
    },
    {
      id: "zotero",
      label: "Zotero",
      href: "https://www.zotero.org/",
      type: "Literaturverwaltung",
    },
  ],

  references: [
    {
      id: "ww",
      title: "Webster, J., & Watson, R. T. (2002). Analyzing the past to prepare for the future: Writing a literature review.",
      note: "Klassische Grundlage für thematische / Konzept-Matrix-Ansätze in der IS-Literatur.",
      href: "https://doi.org/10.2307/4132338",
    },
    {
      id: "prisma2020",
      title: "Page, M. J. et al. (2021). The PRISMA 2020 statement.",
      note: "Reporting systematischer Reviews und Meta-Analysen.",
      href: "https://doi.org/10.1136/bmj.n71",
    },
    {
      id: "tranfield",
      title: "Tranfield, D., Denyer, D., & Smart, P. (2003). Towards a methodology for developing evidence-informed management knowledge.",
      note: "Häufig zitiert für strukturierte Literaturübersichten in der Managementforschung.",
      href: "https://doi.org/10.1080/0020754022000032577",
    },
  ],
};
